<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="login.tests"
    errors="0" failures="1" hostname="" id="" package="login.tests" skipped="2"
    tests="3" time="62.59" timestamp="Tue, 08 Mar 2016 15:04:59 GMT">
  
    <testcase name="step one" time="62.59" assertions="1">  <failure message="Timed out while waiting for element &lt;input[name=loginCompanyId]&gt; to be present for 15000 milliseconds.">    at Object.module.exports.step one (C:\Users\Home\Desktop\Nightwatch\tests\test1.tests.js:12:14)
    at Module.call (C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:63:34)
    at C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:97:29
    at _fulfilled (C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\Home\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (node.js:370:9)</failure>

    
    </testcase>
  
  
    
    <testcase
      name="step two">
      <skipped />
    </testcase>
    
    <testcase
      name="step three">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
